### PR TITLE
map_maker: A tool for autogenerating maps for the bot game.

### PR DESCRIPTION
**Pull request by phho90**
Map maker tool and a quick demo file!

### CODE REVIEW

**Comment by phho90** [comment]
Hi @s-will, @jakobandersen, I've written a tool to auto-generate more complex maps, like districts with different random wall coverages or guaranteed island-free mazes. If you could integrate the map maker in the server, or add a method to unmarshal the map files this program produces we could have some really cool maps for the upcoming tournament!

**Comment by phho90** [comment]
Also, could we change the printing of wall-type tiles to the "\u2588" character?

**Comment by s-will** [comment]
Hi @phho90, this is a really cool extension :+1:

**Comment by s-will** [comment]
I implemented the 'unmarshalling' and pretty printing of the map
@phho90, @jakobandersen: running test.py should work after running demo_map_maker.py

**Comment by s-will** [comment]
@phho90: the maze maker seems to generate complete walls at the right and at the bottom, which does not make much sense; could you fix it? 

Some other observation:
  -- of course, the naive test players are completely lost in the maze
  -- even for smarter players, the 'perfect' maze is a very different challenge compared to random maps

**Comment by phho90** [comment]
@s-will, @jakobandersen  I've fixed the bottom/right wall-making problem. Furthermore, I've added an example for a composite map to the map maker demo.

**Comment by phho90** [comment]
Hi @s-will. Yes, this error occurs for the island-checking algorithm, which works using floodfill. I've now commented away the island checking for the composite map creation. A probably better island-checker would use Dijkstras algorithm to check for an arbitrary non-wall tile if it can reach all other non-wall tiles without walking over a wall tile.

**Comment by s-will** [comment]
This avoids the crash (and cleans up some code redundancy). The inverse flooding can still produce weird maps where almost everything is filled.

**Comment by s-will** [comment]
Hey, the map maker is fully merged into devel-A6 (close PR for cleanup).

**Pull request closed without merging**
