### PR TITLE
Juliawestermayr robot

### PR DESCRIPTION
**Pull request by juliawestermayr**

### CODE REVIEW

**Comment by s-will** [comment]
Hi @juliawestermayr, I suggest to use the branch juliawestermayr-robot only if you want to make more extensions to the robot. Solutions to all other assignments should rather not go here (don't worry about Manhattan/Hamster -- we will finally merge it) but in branch juliawestermayr.

**Comment by juliawestermayr** [comment]
Hi @s-will, thanks for your suggestion, I will try to use only my original branch but I had some issues with this one so I created the juliawestermayr-robot branch together with Jakob. I hopefully will manage to upload the two remaining exercises in my original branch.

**Comment by s-will** [comment]
it's not a big deal; if juliawestermayr does not work, we can also handle juliawestermayr-robot.
I suggested this mostly since 'in general' branches would allow to keep things cleanly separate :)

**Comment by s-will** [comment]
I am going to merge this branch to juliawestermayr and close this PR

**Pull request closed without merging**
